import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/HomeComponents/Navbar";
import Footer from "./_components/HomeComponents/Footer";
import CookieBar from "./_components/HomeComponents/CookieBar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className} data-theme="alsafi">
        <Navbar />

        {children}
        <CookieBar></CookieBar>
        <Footer />
      </body>
    </html>
  );
}

//layout
//usare variabili di stato lookusestate
//lookuseeffect
//localstorage
